/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ganti-password` | `/ganti-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jurnal` | `/jurnal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pengaturan` | `/pengaturan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tema` | `/tema`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tentang-aplikasi` | `/tentang-aplikasi`; params?: Router.UnknownInputParams; } | { pathname: `/api/Apimanager`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ganti-password` | `/ganti-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/jurnal` | `/jurnal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pengaturan` | `/pengaturan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tema` | `/tema`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tentang-aplikasi` | `/tentang-aplikasi`; params?: Router.UnknownOutputParams; } | { pathname: `/api/Apimanager`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ganti-password${`?${string}` | `#${string}` | ''}` | `/ganti-password${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/jurnal${`?${string}` | `#${string}` | ''}` | `/jurnal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pengaturan${`?${string}` | `#${string}` | ''}` | `/pengaturan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tema${`?${string}` | `#${string}` | ''}` | `/tema${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tentang-aplikasi${`?${string}` | `#${string}` | ''}` | `/tentang-aplikasi${`?${string}` | `#${string}` | ''}` | `/api/Apimanager${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ganti-password` | `/ganti-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jurnal` | `/jurnal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pengaturan` | `/pengaturan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tema` | `/tema`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tentang-aplikasi` | `/tentang-aplikasi`; params?: Router.UnknownInputParams; } | { pathname: `/api/Apimanager`; params?: Router.UnknownInputParams; };
    }
  }
}
